name: montepizza
description: Monte sua pizza.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/img/

